### ISSUE TITLE
Per-post TOC control?

### ISSUE THREAD

**Issue by dantecatalfamo** [amzrk2/hugo-theme-fuji#33]
Is it possible to add a per-post TOC front matter variable? I think it would be useful to be able to disable TOC site wide, but enable it if one post is particularly long and has several sub-sections.

**Comment by dsrkafuu** [comment]
@dantecatalfamo 

Due to the mistakes made with the old design in v1, there are a few problems with the logic of enabling or disabling licenses and ToC. For now, you can only disable these two **globally or for specific** posts.

This will soon be fixed in the next release of v2 with new search features. It will be merged into master branch **few hours later**.

You can check out the new [README.md](https://github.com/amzrk2/hugo-theme-fuji/tree/dev#-license-toc-und-comments) for more details.

**Comment by dantecatalfamo** [comment]
Ok, thank you very much!
