### ISSUE TITLE
Gist style issue

### ISSUE THREAD

**Issue by rexarski** [amzrk2/hugo-theme-fuji#48]
When I add a gist with shortcode (or with <script> tag) in a blog post, the displayed gist will be like this:

![gist-css-issue](https://user-images.githubusercontent.com/4172477/94994621-1ea4e880-05dc-11eb-9d19-477ef3a57bf0.png)

See the problem [in action](https://qrui.xyz/post/2018-01-08-de-jong-attractors/).

I found that the white stripe on the right hand side is caused by `width: max-content` in `assets/scss/_primer/markdown/tables.scss`. And the when the dark mode is enabled, the background of the gist (it's a de facto table) is altered to two grey colors which is control by `assets/scss/_fuji-theme/_dark-diff.scss` . I tried to made my own modifications but then I suddenly realized my modifications are subtle for those normal tables implemented with markdown.

Maybe a standalone css for gist?

**Comment by dsrkafuu** [comment]
The Goldenmark that Hugo uses doesn't provide the ability to customize the markdown element class, so it can only be defined directly with the HTML element name, so it affects the gist that inserts directly into the DOM instead of using an iframe.
I tried to fix this by excluding the table that the gist inserted. 9a6032afbeed14701c9acd6923f15ede23eb49db
