### ISSUE TITLE
Is the master branch building?

### ISSUE THREAD

**Issue by hjiawei** [amzrk2/hugo-theme-fuji#50]
I got the following errors when building the latest master. No gulp scripts to build source after recent changes?

> $ cross-env NODE_ENV=production npm run compile
> npm ERR! missing script: compile

**Comment by dsrkafuu** [comment]
Since Hugo Pipes is so well established, we no longer use a slow gulp to build SCSS and JavaScript files. If you overwrite or modify the SCSS/JS files yourself, please use the extended version of Hugo to build the site directly.

Removing project: https://github.com/amzrk2/hugo-theme-fuji/projects/1

**Comment by hjiawei** [comment]
Oh. I see. Thank you for your clarification.
